/*
 * This code was generated by ojc.
 */
import openjava.mop.*;
import openjava.ptree.*;
import openjava.syntax.*;


public class ProfileClass extends openjava.mop.OJClass
{

    public void translateDefinition()
        throws openjava.mop.MOPException
    {
        openjava.mop.OJMethod[] methods = getDeclaredMethods();
        for (int i = 0; i < methods.length; i++) {
            openjava.ptree.StatementList varInit1 = makeStatementList( "double temp = 0.0;" );
            openjava.ptree.StatementList varInit2 = makeStatementList( "int someInt = 0;" );
            varInit1.addAll( methods[i].getBody() );
            varInit1.addAll( varInit2 );
            methods[i].setBody( varInit1 );
        }
    }

    public ProfileClass( openjava.mop.Environment oj_param0, openjava.mop.OJClass oj_param1, openjava.ptree.ClassDeclaration oj_param2 )
    {
        super( oj_param0, oj_param1, oj_param2 );
    }

    public ProfileClass( java.lang.Class oj_param0, openjava.mop.MetaInfo oj_param1 )
    {
        super( oj_param0, oj_param1 );
    }

}
