/*
 * This code was generated by ojc.
 */
package antonio;


import java.util.*;


public class Test
{

    public int bbb()
    {
        return 1;
    }

    class InnerVector extends java.util.Vector
    {

        public int ff = 3;

        public int aaa()
        {
            return bbb();
        }

        public int ccc()
        {
            return 0;
        }

    }

    public void ddd()
    {
        antonio.Test.InnerVector v = new antonio.Test.InnerVector(){
            public int ccc()
            {
                int j = ff;
                return aaa();
            }
        };
        System.err.println( "Result:" + v.ccc() );
    }

    public static void main( java.lang.String[] args )
    {
        (new antonio.Test()).ddd();
    }

}
