/*
 * This code was generated by ojc.
 */
import java.io.*;


public class A
{

    java.io.InputStreamReader r = new java.io.InputStreamReader( System.in );

    java.io.BufferedReader br = new java.io.BufferedReader( r );

    java.lang.String name;

    public void bar()
        throws java.lang.Exception
    {
        System.out.println( "Entering A::bar..." );
        long start = System.currentTimeMillis();
        System.out.print( "Please enter last name: " );
        name = br.readLine();
        long end = System.currentTimeMillis();
        System.out.println( "Leaving A::bar. Time Spent: " + (end - start) / 1000.0 + "s" );
    }

    public void foo()
        throws java.lang.Exception
    {
        System.out.println( "Entering A::foo..." );
        long start = System.currentTimeMillis();
        System.out.print( "Please enter first name: " );
        name = br.readLine();
        bar();
        long end = System.currentTimeMillis();
        System.out.println( "Leaving A::foo. Time Spent: " + (end - start) / 1000.0 + "s" );
    }

}
