/*
 * This code was generated by ojc.
 */
public class HW1
{

    public static void main( java.lang.String[] args )
        throws java.lang.Exception
    {
        System.out.println( "Entering HW1::main..." );
        long start = System.currentTimeMillis();
        A a = new A();
        B b = new B();
        C c = new C();
        a.foo();
        b.foo();
        c.foo();
        a.foo();
        long end = System.currentTimeMillis();
        System.out.println( "Leaving HW1::main. Time Spent: " + (end - start) / 1000.0 + "s" );
    }

}
