/*
 * This code was generated by ojc.
 */
import openjava.mop.*;
import openjava.ptree.*;
import openjava.syntax.*;


public class ProfileClass extends openjava.mop.OJClass
{

    public void translateDefinition()
        throws openjava.mop.MOPException
    {
        openjava.mop.OJMethod[] methods = getDeclaredMethods();
        java.lang.String className = getSimpleName();
        for (int i = 0; i < methods.length; i++) {
            openjava.ptree.StatementList start = makeStatementList( "System.out.println( \"Entering " + className + "::" + methods[i].getName() + "...\" ); long start = System.currentTimeMillis(); " );
            openjava.ptree.StatementList end = makeStatementList( "long end = System.currentTimeMillis(); System.out.println( \"Leaving " + className + "::" + methods[i].getName() + ". Time Spent: \" + ((end - start)/1000.0) + \"s\");" );
            start.addAll( methods[i].getBody() );
            start.addAll( end );
            methods[i].setBody( start );
        }
    }

    public ProfileClass( openjava.mop.Environment oj_param0, openjava.mop.OJClass oj_param1, openjava.ptree.ClassDeclaration oj_param2 )
    {
        super( oj_param0, oj_param1, oj_param2 );
    }

    public ProfileClass( java.lang.Class oj_param0, openjava.mop.MetaInfo oj_param1 )
    {
        super( oj_param0, oj_param1 );
    }

}
